name: Ejecutar Bot de Pedido

on:
  workflow_dispatch:
    inputs:
      datos:
        description: 'Datos del pedido'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3

      - name: Ejecutar script de Python
        run: |
          echo "Recibiendo pedido: ${{ github.event.inputs.datos }}"
          # Aqui es donde correra tu script mas adelante
